#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

branch=$(git rev-parse --symbolic --abbrev-ref HEAD)
if [[ "master" == "$branch" || "test" == "$branch" || "develop" == "$branch" || "$branch" =~ "release" ]]
then
  echo "禁止直接commit到此分支"
  exit 1
fi
exit 0
